name: Compile SM64 DS Port

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies and DevkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libpng-dev tools-common
          # Descarga e instala devkitARM de forma automatizada
          wget https://github.com
          sudo apt-get install ./devkitpro-pacman.deb
          sudo dkp-pacman -Syy --noconfirm
          sudo dkp-pacman -S nds-dev --noconfirm

      - name: Set Environment Variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV

      - name: Compile ROM
        run: |
          # Compila el proyecto usando las herramientas nativas
          make

      - name: Upload NDS Rom Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sm64-ds-port
          path: |
            *.nds
            build/*.nds
