name: Compile SM64 DS Port

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create local output directory
      run: mkdir -p out

    - name: Compile with Docker Volume
      run: |
        docker build -t sm64ds-compiler .
        docker run --rm -v ${{ github.workspace }}/out:/app/out -v ${{ github.workspace }}/out:/workspace/out sm64ds-compiler || true
        
    - name: Check inside out folder
      run: |
        ls -R out/ || true
        find . -name "*.nds" || true

    - name: Upload NDS Rom Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sm64-ds-port
        path: |
          out/
          **/*.nds
